deleteall;
clear;
switchtolayout;
clearfunctions;
#find lsf files
for(k = 0;k < @num_files; k = k + 1) {
	
    # Find lsf files generated
	files = splitstring(ls("."), "\n");
	number_of_lsf = 0;
	for (i=1:length(files)) {
		file = files{i};
		if (findstring(file, ".run.lsf") >= 0) {
		    number_of_lsf = number_of_lsf + 1;
		} else {
		    files{i} = "null";
		}
	}
	lsf_files = cell(number_of_lsf);
	count = 1;
	for (i=1:length(files)) {
		file = files{i};
		if (file != "null") {
		    lsf_files{count} = file;
		    count = count + 1;
		}
	}
	filename = lsf_files{k+1}; # Grab one of the lsf files

	# Generate filenames for supplementary files we are about to create	
	lms_filename = replacestring(filename, ".lsf", ".lms");
	
	#need to store iterator to file b/c feval() destroys local environment variables
    write("iterator.txt",num2str(k), "overwrite");

	# evaluate script to generate lms file, 
	feval(filename);
    
	#read back iterator, this needs to be done or you will enter an infinite loop
	k = read("iterator.txt");
	k = str2num(k);
}

#create corresponding slurm file to run the generated lms file
print("Execution completed.");